name: Jorg
favicon: null
layout_spectrum: 0.8262613040860742
typography_spectrum: 0.5225244970060885
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.375
  lightness: 0.6871835398487747
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
